nmelhado/league-page

README.md
TRAINING_WHEELS.md
src/routes/managers/managers.js

The managers section seems to be the trickiest, so I'm adding a few references to the more detailed TRAING WHEELS guide

reference training wheel guide in README and in managers.js

---

src/lib/utils/helperFunctions/leagueAwards.js

Fixes an issue that affected leagues with playoffs that weren't 3 rounds long

Flexible brackets

---

src/lib/Managers/Manager.svelte
src/lib/Managers/ManagerFantasyInfo.svelte
src/lib/Managers/ManagerRow.svelte
src/routes/managers/managers.js

This provides one of the feature enhancements recommended in enhancement https://github.com/nmelhado/league-page/issues/18
Make these fields nullable in `/src/routes/managers/managers.js`
- location
- fantasyStart
- favoriteTeam
- mode
- favoritePlayer
- valuePosition
- rookieOrVets

make certain managers.js fields nullable

---

README.md
src/lib/Footer.svelte
src/lib/Matchups/Brackets.svelte
src/lib/Matchups/BracketsColumn.svelte
src/lib/Matchups/Matchup.svelte
src/lib/Matchups/MatchupWeeks.svelte
src/lib/Matchups/MatchupsAndBrackets.svelte
src/lib/components.js
src/lib/stores.js
src/lib/utils/helper.js
src/lib/utils/helperFunctions/leagueBrackets.js
src/lib/utils/helperFunctions/leagueMatchups.js
src/routes/matchups/index.svelte

Display playoff brackets, with functionality to click on matchups and view them.

Show bracket

---

src/lib/Awards/Awards.svelte
src/lib/Managers/ManagerAwards.svelte

Also add flexibility if there's no last place to the Managers pages

Flexible toilet bowl

---

TRAINING_WHEELS.md
package.json
src/lib/Footer.svelte
src/lib/version.js
src/routes/api/checkVersion.js

Add a message in the footer to tell users that their League Page is out of date

add update message when League Page is out of date

---

CHANGELOG.md
TRAINING_WHEELS.md
src/routes/index.svelte

Fixes the week displayed in the homepage and adds some instructions to the Training Wheels guide

fix homepage and add update Training Wheels

---

CHANGELOG.md
package.json
src/lib/Managers/Manager.svelte
src/lib/Managers/ManagerFantasyInfo.svelte
src/lib/Managers/ManagerRow.svelte
src/lib/utils/leagueInfo.js
src/lib/version.js

Fallbacks are displayed for any nullable field that is displayed in the all managers page.
Nullable fields are omitted in the manager detail page (except for location which has a fallback of "Undisclosed Location")
Fix for https://github.com/nmelhado/league-page/issues/47

made more manager fields nullable and handling nullable fields better

---

CHANGELOG.md
package.json
src/lib/Managers/Manager.svelte
src/lib/Managers/index.svelte
src/lib/Matchups/MatchupsAndBrackets.svelte
src/lib/PowerRankings/PowerRankingsDisplay.svelte
src/lib/PowerRankings/index.svelte
src/lib/Records/index.svelte
src/lib/Rosters/Roster.svelte
src/lib/Rosters/Rosters.svelte
src/lib/Transactions/Transaction.svelte
src/lib/Transactions/TransactionMove.svelte
src/lib/Transactions/Transactions.svelte
src/lib/Transactions/TransactionsPage.svelte
src/lib/utils/helperFunctions/leagueTransactions.js
src/lib/utils/helperFunctions/players.js
src/lib/version.js
src/routes/records/index.svelte
src/routes/rosters/index.svelte
src/routes/transactions/index.svelte

Reverts nmelhado/league-page#53

Revert "load transaction and player updates in the background"

---

CHANGELOG.md
package.json
src/lib/Managers/Manager.svelte
src/lib/Managers/index.svelte
src/lib/Matchups/MatchupsAndBrackets.svelte
src/lib/PowerRankings/PowerRankingsDisplay.svelte
src/lib/PowerRankings/index.svelte
src/lib/Records/index.svelte
src/lib/Rosters/Roster.svelte
src/lib/Rosters/Rosters.svelte
src/lib/Transactions/Transaction.svelte
src/lib/Transactions/TransactionMove.svelte
src/lib/Transactions/Transactions.svelte
src/lib/Transactions/TransactionsPage.svelte
src/lib/utils/helperFunctions/leagueTransactions.js
src/lib/utils/helperFunctions/players.js
src/lib/version.js
src/routes/records/index.svelte
src/routes/rosters/index.svelte
src/routes/transactions/index.svelte

This pr significantly improves the performance of League Page
- Use stale data for players and transactions
- Load fresh data in the background
- When the new data is fetched, update the UI to reflect the changes

Cache transactions v2

---

CHANGELOG.md
package.json
src/lib/Matchups/BracketsColumn.svelte
src/lib/Matchups/Matchup.svelte
src/lib/version.js
src/routes/api/fetch_players_info.js

Fix for bug https://github.com/nmelhado/league-page/issues/57

pull in IDP projections and update projections when the players are refreshed in the background

---

.gitignore
CHANGELOG.md
package.json
src/lib/Managers/ManagerFantasyInfo.svelte
src/lib/Matchups/BracketsColumn.svelte
src/lib/Matchups/Matchup.svelte
src/lib/PowerRankings/PowerRankingsDisplay.svelte
src/lib/Rosters/Roster.svelte
src/lib/Rosters/RosterRow.svelte
src/lib/Transactions/TransactionMove.svelte
src/lib/Transactions/TransactionsPage.svelte
src/lib/utils/helperFunctions/predictOptimalScore.js
src/lib/version.js
src/routes/api/fetch_players_info.js

Second fix for issue https://github.com/nmelhado/league-page/issues/60

reduce the length of variable names in order reduce the payload size

---

CHANGELOG.md
package.json
src/lib/Managers/ManagerAwards.svelte
src/lib/Matchups/BracketsColumn.svelte
src/lib/Standings/Standing.svelte
src/lib/Standings/index.svelte
src/lib/components.js
src/lib/stores.js
src/lib/utils/helper.js
src/lib/utils/helperFunctions/leagueStandings.js
src/lib/utils/tabs.js
src/lib/version.js
src/routes/awards/index.svelte
src/routes/standings/index.svelte

Implementing feature suggestion https://github.com/nmelhado/league-page/issues/59. Adds a standings tab with regular season standings.

add standings tab

---

CHANGELOG.md
README.md
TRAINING_WHEELS.md
package.json
src/lib/BlogPosts/Comments.svelte
src/lib/BlogPosts/CreateComment.svelte
src/lib/BlogPosts/HomePost.svelte
src/lib/BlogPosts/Post.svelte
src/lib/BlogPosts/Posts.svelte
src/lib/utils/helper.js
src/lib/utils/helperFunctions/universalFunctions.js
src/lib/utils/leagueInfo.js
src/lib/version.js
src/routes/api/addBlogComments/[id].js
src/routes/api/getBlogComments/[id].js
src/routes/api/getBlogPosts.js
src/routes/blog/index.svelte

Add the option to leave comments on blog posts
- **REQUIRES A NEW TYPE OF CONTENTFUL API KEY**
- This will break previous contentful integrations because the new key is not compatible with the old read only API
- To fix previous integrations just follow the directions to get a content management API and replace your secret key with the new value

Blog comments

---

CHANGELOG.md
package.json
src/lib/BlogPosts/Posts.svelte
src/lib/Records/AllTimeRecords.svelte
src/lib/Records/PerSeasonRecords.svelte
src/lib/Records/RecordsAndRankings.svelte
src/lib/Records/index.svelte
src/lib/utils/helperFunctions/leagueRecords.js
src/lib/version.js
src/routes/records/index.svelte

Filling some of the requests from feature request https://github.com/nmelhado/league-page/issues/70
features filled:
- [x ] Closest Matchups
- [x ] Biggest blowouts

add blowout and narrowest victories

---

CHANGELOG.md
package.json
src/lib/utils/helperFunctions/leagueRecords.js
src/lib/version.js

Fixes the issue reported in issue https://github.com/nmelhado/league-page/issues/77

display correct week in records

---

CHANGELOG.md
package.json
src/lib/Records/PerSeasonRecords.svelte
src/lib/Records/RecordsAndRankings.svelte
src/lib/version.js

Fix the second issue reported in issue https://github.com/nmelhado/league-page/issues/77

fix NaN bug in records

---

CHANGELOG.md
package-lock.json
package.json
src/lib/Records/AllTimeRecords.svelte
src/lib/Records/PerSeasonRecords.svelte
src/lib/Records/RecordsAndRankings.svelte
src/lib/utils/helperFunctions/leagueRecords.js
src/lib/utils/leagueInfo.js
src/lib/version.js

This includes only the commits for the PPG column (and is cleaner than the other pull request I had previously opened)

Adds PPG Column to Season-Long Records Tables

---

CHANGELOG.md
package-lock.json
package.json
src/lib/utils/helperFunctions/leagueAwards.js
src/lib/version.js

Fix for bug reported in issue https://github.com/nmelhado/league-page/issues/95

fix bug in trophies page

---

CHANGELOG.md
README.md
TRAINING_WHEELS.md
package-lock.json
package.json
src/lib/version.js
src/routes/api/getBlogPosts.js

When you're working on a draft post, it was still being returned, this fix filters out non-published posts

fix blog post bug with draft posts

---

CHANGELOG.md
package-lock.json
package.json
src/lib/Managers/ManagerAwards.svelte
src/lib/version.js

bug rc: records now contains regular season and playoff values, needed to select regular season object in manager page

fix manager page bug

---

CHANGELOG.md
TRAINING_WHEELS.md
package-lock.json
package.json
src/lib/utils/helperFunctions/getBlogPosts.js
src/lib/version.js

* fix blog header bug and update docs
* fix unintentional link

fix blog header bug and update docs (#167)

---

CHANGELOG.md
package-lock.json
package.json
src/lib/Managers/Manager.svelte
src/lib/version.js

manager transactions were not using the new manager ID field on the manager pages

fix manager transaction bug

---

CHANGELOG.md
package-lock.json
package.json
src/lib/Awards/Awards.svelte
src/lib/BlogPosts/HomePost.svelte
src/lib/BlogPosts/Post.svelte
src/lib/BlogPosts/Posts.svelte
src/lib/Managers/Manager.svelte
src/lib/PowerRankings/PowerRankingsDisplay.svelte
src/lib/Rosters/RosterSorter.svelte
src/lib/Standings/Standing.svelte
src/lib/Standings/index.svelte
src/lib/utils/helperFunctions/leagueAwards.js
src/lib/utils/helperFunctions/leagueBrackets.js
src/lib/utils/helperFunctions/leagueDrafts.js
src/lib/utils/helperFunctions/leagueMatchups.js
src/lib/utils/helperFunctions/leagueRecords.js
src/lib/utils/helperFunctions/leagueRosters.js
src/lib/utils/helperFunctions/leagueStandings.js
src/lib/utils/helperFunctions/universalFunctions.js
src/lib/utils/leagueInfo.js
src/lib/version.js
src/routes/+page.svelte
src/routes/blog/+page.js
src/routes/blog/+page.svelte

Roster order was getting messed up on the standings page. In order to fix that, I've converted rosters into an object instead of an array.

Roster order bug

---

CHANGELOG.md
package-lock.json
package.json
src/lib/Rivalry/ComparissonBar.svelte
src/lib/Rivalry/index.svelte
src/lib/version.js
src/theme/_smui-theme.scss
src/theme/dark/_smui-theme.scss

Added fpts/game and win % stats to the rivalry page and highlighted which manager is winning in each stat comparison bar

improve rivalry page

---

src/lib/Resources.svelte

Hey, I hope you don't mind me adding my site to the league-page resources.  It's a free data science focused trade value site.  More about it here https://www.fantasycalc.com/frequently-asked-questions.
I would also be interested in adding power rankings, waiver wire rankings, and/or trade grades based off of the FantasyCalc values, if that's something you'd be interested in.
I'm setting up the league page for my own league now, and it looks great.  Can't wait to show my league mates.

Update Fantasy Resource

---

CHANGELOG.md
package-lock.json
package.json
src/lib/BlogPosts/FullPost.svelte
src/lib/BlogPosts/HomePost.svelte
src/lib/BlogPosts/Post.svelte
src/lib/components.js
src/lib/utils/helperFunctions/leagueDrafts.js
src/lib/version.js
src/routes/blog/[slug]/+page.js
src/routes/blog/[slug]/+page.svelte

Fix the bug related to auction amounts not showing up. Also change blog handling to make links to individual blog posts and make the current displays into previews.

fix auction amount bug and improve blog handling

---

CHANGELOG.md
package-lock.json
package.json
src/lib/version.js

Forgot to bump the version and add to the Changelog for yesterday's changes. Doing that now so that people get the update message on their pages.

bump version from previous changes

---

CHANGELOG.md
package-lock.json
package.json
src/lib/utils/helperFunctions/leagueRecords.js
src/lib/version.js

Thanks @boprice for the bug report and the recommended fix!

fix duplicated playoff stat issue

---

CHANGELOG.md
package-lock.json
package.json
src/lib/BlogPosts/FullPost.svelte
src/lib/version.js

fix full blog post issue
